### ISSUE TITLE
Swipe Event not triggered on TouchScreen + Chrome Device Toolbar

### ISSUE THREAD

**Issue by Listor** [benmajor/jQuery-Touch-Events#118]
Hi there, I have an issue with your lib. My ThinkPad Ultrabook has a native TouchMonitor. The Swipe Events are not triggered on the demo page http://lincweb.co.uk/labs/jquery-touch-events/demo/

When I use the chrome device toolbar to emulate swipes it doesn't work either. On my Smartphone it works correctly but somehow the events are not triggered correctly and hardly to test / debug this way if chrome doesn't work either.

The Chrome Version I use is 54.0.2840.99 m. This is a Win10 Thinkpad. If you need any further informations please let me know. 

There are lots of other Lib's that handle it correctly for instance http://www.w3schools.com/jquerymobile/jquerymobile_events_touch.asp they handle the event correctly on my touchscreen and in Chrome Device Toolbar. Maybe you can look there to figure out what the problem is.

**Comment by benmajor** [comment]
Thanks for the issue. Can you tell me what the full value of the User Agent is when you receive this error? It will certainly help to debug the problem, but I suspect it's related to the `isChromeDesktop` check:

    isChromeDesktop = (agent.indexOf('chrome') > -1 && ((agent.indexOf('windows') > -1) || (agent.indexOf('macintosh') > -1) || (agent.indexOf('linux') > -1)) && agent.indexOf('mobile') < 0 && agent.indexOf('android') < 0)

Thanks,
Ben.

**Comment by Listor** [comment]
Hey Ben,

my user Agent is 

`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36`

yeah if you check for the user agent and assume that it is not able to touch that might be the issue. I had a smiliar issue trying to find out if the device can use touch or not. But this seams to be a tough call since last time i checked chrome always says it has the ability to, even though no touch display was attached to.

not sure if you really need a condition here and might not just listen on the events and handle them if they come in ? 

Best,
Michael

**Comment by benmajor** [comment]
Thanks Michael,

Yes it looks like there is an issue in assigning the `isChromeDesktop` flag with that particular UserAgent. 

In an ideal world, we could handle the touch and click events in the same handlers, but as you've said, Chrome is annoying in that the desktop version will trigger multiple events (i.e. both `touchstart` and `mousedown`) even when both are not natively supported by the device. For now, I think we still need to retain the condition :(

I'll have a look at updating the condition flag.

Thanks,
Ben.

**Comment by Listor** [comment]
yeah. i think i was in that hell ^^ with the multiple events when i recall correctly so i guess you are right about the condition.

anyway thx for your quick reply. if you need further assistance just let me know.

Best,
Michael

**Comment by benmajor** [comment]
So, I've been doing some more research into this topic, and I think the following condition should resolve the issue you're experiencing. It also means that the `touchCapable` condition is reduced to something far more manageable: 

    var ua           = navigator.userAgent,
		isChrome     = /chrome/i.exec(ua),
		isAndroid    = /android/i.exec(ua),
		touchCapable = 'ontouchstart' in window && !(isChrome && !isAndroid),

**Comment by Listor** [comment]
hey ben,

as far as i can tell this looks promising. if you want me to test it you can provide a test build for me.

Best,
Michael

**Comment by benmajor** [comment]
Thanks @Listor,

Could you try the new JS file I've added to the dev branch?
https://github.com/benmajor/jQuery-Touch-Events/blob/dev/jquery.mobile-events.js

**Comment by Listor** [comment]
hey,

isChromeDesktop  is not defined. guess i'm missing something ??

**Comment by benmajor** [comment]
No, it was my fault :/ I forgot another reference to `isChromeDesktop` (which is now `touchCapable`). It should be fixed in the latest `dev` branch commit:

https://github.com/benmajor/jQuery-Touch-Events/commit/1bff051cd727e92b1fbff7934bde2895bab5cce2

**Comment by Listor** [comment]
i guess another commit needs to be done. touch_capable is not defined. think it should be settings.touch_capable shouldn't it ? :D

**Comment by benmajor** [comment]
What line are you getting that error on?

**Comment by benmajor** [comment]
Sorry, it's been a long day ;)

Try this one: https://github.com/benmajor/jQuery-Touch-Events/commit/950bfae989b8595c2affeceaddc76124fde31582

**Comment by Listor** [comment]
hehe no worries. we've all been there :D but unfortuneatly it is still not working. touchCapable is false as you can see in the screen i attached
![touchevents](https://cloud.githubusercontent.com/assets/4637866/22509718/825b5652-e88f-11e6-8227-32338455500e.JPG)

**Comment by benmajor** [comment]
It appears that recent versions of Chrome correctly fixed the issue for non-touch devices.  For example:

    'ontouchstart' in window // now == false

I think this suffices now, can you check the latest push to `dev` for me? https://github.com/benmajor/jQuery-Touch-Events/commit/ee3be3ec8089ca907c9facaf43df663f63da6a3a

**Comment by Listor** [comment]
yeah looks like they adressed it....

i think that's it. my tests were successful. looks good to me :)

**Comment by benmajor** [comment]
Excellent, will push to master for 1.0.8 this evening!

Thanks for your help, @Listor.

**Comment by Listor** [comment]
no problem. great thank you ! :)

**Comment by benmajor** [comment]
Now pushed to production: https://github.com/benmajor/jQuery-Touch-Events/tree/master/src/1.0.8
